# Generated by Django 5.2.8 on 2025-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expertise', models.CharField(max_length=50)),
                ('trainer_photo', models.ImageField(blank=True, null=True, upload_to='trainer_photos/')),
            ],
        ),
    ]
